name: React CI/CD
on: 
  # push: 
  #   branches: main
  #   paths-ignore:
  #     - ./github/workflows/*

  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  run-reusable-workflow:
    name: "React CI/CD"
    uses: dhruv-development/reusable_workflows/.github/workflows/react-ci-cd.yml@main
    with:
      role-assume: "arn:aws:iam::410454990341:role/GitHubActionsRole"
      AWS_REGION: "us-east-2"
      ECR_REPO: "react-new"
      TASK_DEFINITION: "react-django-task-definition"
      CONTAINER_NAME: "react-django"
      CLUSTER: "react-django"
      SERVICE: "react-django-service"
      S3_Bucket: "react-bucket-v1"
